version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - durationcheck
    - errorlint
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - makezero
    - nakedret
    - noctx
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - wsl
  settings:
    gocognit:
      min-complexity: 30
    gocritic:
      disabled-tags:
        - opinionated
        - experimental
    gocyclo:
      min-complexity: 30
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
