version: "2"

run:
  timeout: 5m
  tests: true
  concurrency: 4
  go: '1.21'

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - bodyclose
    - gocritic
    - ineffassign
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

output:
  # The formats used to render issues.
  formats:
    # Prints issues in a text format with colors, line number, and linter name.
    # This format is the default format.
    text:
      # Output path can be either `stdout`, `stderr` or path to the file to write to.
      # Default: stdout
      path: ./path/to/output.txt
      # Print linter name in the end of issue text.
      # Default: true
      print-linter-name: false
      # Print lines of code with issue.
      # Default: true
      print-issued-lines: true
      colors: true
